site_name: HomotopicAI
theme:
  name: bootstrap386
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
  custom_dir: overrides
  static_templates:
    - sitemap.xml
    - CNAME
  palette:
    scheme: dark

extra_css:
  - assets/css/custom.css

markdown_extensions:
  - toc
  - tables
  - fenced_code
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Problem: problem.md
  - Solution: solution.md
  - Technical Documentation:
    - Foundations: foundations.md
    - Design: design.md
    - Energy Efficiency: energy.md
    - Programming: programming.md
    - Applications: applications.md
    - Performance: performance.md
  - Product:
    - Overview: product/overview.md
    - Technical Specs: product/specs.md
    - Use Cases: product/use-cases.md

# Site configuration
site_url: https://homotopicai.com
repo_url: https://github.com/Homotopic-AI/homotopicai
edit_uri: edit/main/docs/

plugins:
  - search

copyright: '(C) 2025 HOMOTOPIC AI - ALL RIGHTS RESERVED'
