site_name: HomotopicAI
theme:
  name: bootstrap386
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  static_templates:
    - sitemap.xml
    - CNAME

markdown_extensions:
  - toc
  - tables
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Product: 
    - Overview: product/overview.md
    - Technical Specs: product/specs.md
    - Use Cases: product/use-cases.md
  - Developer:
    - SDK & Tools: developer/sdk.md
    - Documentation: developer/docs.md
    - Community: developer/community.md
  - Company:
    - About: company/about.md
    - Blog: company/blog.md
    - Careers: company/careers.md
  - Support:
    - Resources: support/resources.md
    - Contact: support/contact.md
  - Legal:
    - Privacy: legal/privacy.md
    - Terms: legal/terms.md
    - Ethics: legal/ethics.md

# Site configuration
site_url: https://homotopicai.com
repo_url: https://github.com/Homotopic-AI/homotopicai
edit_uri: edit/main/docs/

plugins:
  - search
