site_name: HomotopicAI
theme:
  name: simple-blog
  nav_style: light
  navigation_depth: 2

extra_css:
  - assets/css/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css
  - https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap

markdown_extensions:
  - toc
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Manifesto: manifesto.md
  - Problems:
    - Overview: problem.md
    - Technical Problems: problems/technical.md
    - Economic Problems: problems/economic.md
    - Social Problems: problems/social.md
    - Environmental Problems: problems/environmental.md
  - Solution: solution.md
  - Technical Documentation:
    - Foundations: foundations.md
    - Hardware: hardware.md
    - Software: software.md
    - Design: design.md
    - Energy Efficiency: energy.md
    - Programming: programming.md
    - Applications: applications.md
    - Performance: performance.md
  - Product:
    - Overview: product/overview.md
    - Technical Specs: product/specs.md
    - Use Cases: product/use-cases.md

# Site configuration
site_url: https://homotopicai.com
site_description: Advanced Computing Solutions with MAP™ Brick
site_author: HomotopicAI
copyright: Copyright &copy; 2025 HomotopicAI

plugins:
  - search
